# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# pre-commit sample-config | out-file .pre-commit-config.yaml -encoding utf8
# pre-commit install
# pre-commit run --all-files
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace

  - id: end-of-file-fixer

  - id: check-yaml

  - id: check-json

  - id: check-case-conflict

  - id: check-docstring-first

  - id: name-tests-test

  - id: fix-encoding-pragma
    args: ['--remove']

  - id: forbid-new-submodules

  - id: mixed-line-ending
    args: ['--fix=lf']
    description: Forces to replace line ending by the UNIX 'lf' character.

  - id: check-added-large-files
    args: ['--maxkb=500']

  - id: no-commit-to-branch
    args: [--branch, master]

- repo: https://github.com/ambv/black
  rev: 21.11b1
  hooks:
  - id: black
    language_version: python3.9

- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.6.0
  hooks:
    - id: reorder-python-imports
